[project]
name = "epub"
version = "0.1.1"
description = "epub manipulation package"
authors = [
	{ name = "Moses Lara", email = "mlara417@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "typer==0.13.0",
    "lxml==5.3.0"
]

[project.scripts]
epub = "cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "pyproject.toml"
pattern = 'version = "{version}"'

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.1"