name: Example Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref || github.ref_name }}


      - name: Setup Git Config
        uses: qoomon/actions--setup-git@v1.1.1
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Tools
        run: |
          pip install hatch commitizen

      - name: Bump Version Based on Conventional Commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          
          cz check -m "$COMMIT_MESSAGE"
          cz bump --yes

      - name: Commit Version Bump
        run: |
          git push origin ${{ github.ref_name }}
          git push origin --tags
      
      - name: Build and Publish
        env:
          HATCH_INDEX_REPO: https://test.pypi.org/legacy/
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          hatch build
          hatch publish --no-prompt
