name: Example Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Tools
        run: |
          pip install hatch commitizen

      - name: Bump Version Based on Conventional Commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cz bump --yes
          git push origin main --tags

      - name: Build and Publish
        env:
          PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          hatch build
          hatch publish
