name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.0.1'

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Tools
        run: |
          pip install commitizen
      
      - name: Generate Release Notes
        env:
          RELEASE_VERSION: ${{ inputs.version }}
        run: |
          if [ -z "$RELEASE_VERSION" ]; then
            RELEASE_VERSION=$(git describe --tags)
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$(cz changelog --incremental --unreleased-version ${{ env.RELEASE_VERSION }} --dry-run)" >> $GITHUB_ENV
          cz changelog --incremental --unreleased-version ${{ env.RELEASE_VERSION }}

      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_VERSION }} \
            --title "Release ${{ env.RELEASE_VERSION }}" \
            --notes "${{ env.RELEASE_NOTES }}" \
            --generate-notes \
            --prerelease