name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Tools
        run: |
          pip install commitizen
      
      - name: Generate Release Notes
        run: |
          echo "RELEASE_NOTES=$(cz changelog --dry-run)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_VERSION }} \
            --title "Release ${{ env.RELEASE_VERSION }}" \
            --notes "${{ env.RELEASE_NOTES }}" \
            --generate-notes
            --prerelease