name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.0.1'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.62.0
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Tools
        run: |
          pip install commitizen==3.31.0
      
      - name: Generate Release Notes
        env:
          RELEASE_VERSION: ${{ inputs.version }}
        run: |
          if [ -z "${{ env.RELEASE_VERSION }}" ]; then
            RELEASE_VERSION=$(git describe --tags)
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$(cz changelog --incremental --unreleased-version ${{ env.RELEASE_VERSION }} --dry-run)" >> $GITHUB_ENV
          cz changelog --incremental --unreleased-version "${{ env.RELEASE_VERSION }}"

      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_VERSION }} \
            --title "Release ${{ env.RELEASE_VERSION }}" \
            --notes "${{ env.RELEASE_NOTES }}" \
            --generate-notes \
            --prerelease